SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE T_ITEM_HASH_MAPP;
DROP TABLE T_FORMULA;
DROP TABLE T_ITEM;
DROP TABLE T_HASH_TAG;
DROP TABLE T_MEMBER;




/* Create Tables */

CREATE TABLE T_ITEM
(
	-- 아이템 아이디(UUID)
	ITEM_ID varchar(128) NOT NULL COMMENT '아이템 아이디(UUID)',
	-- 아이템 이름
	ITEM_NM varchar(256) NOT NULL COMMENT '아이템 이름',
	PRIMARY KEY (ITEM_ID)
);


CREATE TABLE T_ITEM_HASH_MAPP
(
	-- 아이템 아이디(UUID)
	ITEM_ID varchar(128) NOT NULL COMMENT '아이템 아이디(UUID)',
	-- 해시태그 아이디(UUID)
	HASH_ID varchar(128) NOT NULL COMMENT '해시태그 아이디(UUID)',
	PRIMARY KEY (ITEM_ID, HASH_ID)
);


CREATE TABLE T_HASH_TAG
(
	-- 해시태그 아이디(UUID)
	HASH_ID varchar(128) NOT NULL COMMENT '해시태그 아이디(UUID)',
	-- 해시태그명
	HASH_NM varchar(512) NOT NULL COMMENT '해시태그명',
	PRIMARY KEY (HASH_ID)
);


CREATE TABLE T_FORMULA
(
	-- 재료 A - 아이템 아이디(UUID)
	MATERIAL_A_ITEM_ID varchar(128) NOT NULL COMMENT '재료 A - 아이템 아이디(UUID)',
	-- 재료 B - 아이템 아이디(UUID)
	MATERIAL_B_ITEM_ID varchar(128) NOT NULL COMMENT '재료 B - 아이템 아이디(UUID)',
	-- 조합결과 아이템 아이디(UUID)
	OUTPUT_ITEM_ID varchar(128) NOT NULL COMMENT '조합결과 아이템 아이디(UUID)',
	PRIMARY KEY (MATERIAL_A_ITEM_ID, MATERIAL_B_ITEM_ID, OUTPUT_ITEM_ID)
);


CREATE TABLE T_MEMBER
(
	-- 회원아이디
	MEMBER_ID varchar(32) NOT NULL COMMENT '회원아이디',
	-- 회원명
	MEMBER_NM varchar(32) NOT NULL COMMENT '회원명',
	-- 회원비밀번호(SHA512)
	MEMBER_PASSWD varchar(512) NOT NULL COMMENT '회원비밀번호(SHA512)',
	PRIMARY KEY (MEMBER_ID)
);



/* Create Foreign Keys */

ALTER TABLE T_ITEM_HASH_MAPP
	ADD FOREIGN KEY (ITEM_ID)
	REFERENCES T_ITEM (ITEM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_FORMULA
	ADD FOREIGN KEY (MATERIAL_A_ITEM_ID)
	REFERENCES T_ITEM (ITEM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_FORMULA
	ADD FOREIGN KEY (MATERIAL_B_ITEM_ID)
	REFERENCES T_ITEM (ITEM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_FORMULA
	ADD FOREIGN KEY (OUTPUT_ITEM_ID)
	REFERENCES T_ITEM (ITEM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_ITEM_HASH_MAPP
	ADD FOREIGN KEY (HASH_ID)
	REFERENCES T_HASH_TAG (HASH_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



